### ISSUE TITLE
can't build the package myself

### ISSUE THREAD

**Issue by sverx** [yuv422/z80editor#9]
I installed maven, I had never used that before, to build the package myself

when I do

`mvn package`

I just get

`[ERROR] Internal error: java.lang.RuntimeException: Could not resolve target platform specification artifact org.efry.z80editor:org.efry.z80editor.target:target:1.0.0-SNAPSHOT -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Could not resolve target platform specification artifact org.efry.z80editor:org.efry.z80editor.target:target:1.0.0-SNAPSHOT
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: Could not resolve target platform specification artifact org.efry.z80editor:org.efry.z80editor.target:target:1.0.0-SNAPSHOT
	at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.addTargetArtifact(DefaultTargetPlatformConfigurationReader.java:389)
	at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.setTarget(DefaultTargetPlatformConfigurationReader.java:342)
	at org.eclipse.tycho.core.resolver.DefaultTargetPlatformConfigurationReader.getTargetPlatformConfiguration(DefaultTargetPlatformConfigurationReader.java:75)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.setupProject(DefaultTychoResolver.java:87)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:90)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
`

what's wrong with it?

**Comment by sverx** [comment]
after having added the missing build files, I get this error:

```
[INFO] Compiling 367 source files to /home/user/github-repositories/z80editor/org.efry.z80editor/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] org.efry.z80editor.parent .......................... SUCCESS [  0.104 s]
[INFO] org.efry.z80editor ................................. FAILURE [01:14 min]
[INFO] org.efry.z80editor.ide ............................. SKIPPED
[INFO] org.efry.z80editor.ui .............................. SKIPPED
[INFO] org.efry.z80editor.target .......................... SKIPPED
[INFO] org.efry.z80editor.feature ......................... SKIPPED
[INFO] org.efry.z80editor.repository ...................... SKIPPED
[INFO] org.efry.z80editor.tests ........................... SKIPPED
[INFO] org.efry.z80editor.ui.tests ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:44 min
[INFO] Finished at: 2020-05-18T14:44:43+01:00
[INFO] Final Memory: 220M/957M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:1.5.1:compile (default-compile) on project org.efry.z80editor: Compilation failure: Compilation failure:
[ERROR] /home/user/github-repositories/z80editor/org.efry.z80editor/xtend-gen/org/efry/z80editor/Z80StandaloneSetup.java:[12]
[ERROR] public class Z80StandaloneSetup extends Z80StandaloneSetupGenerated {
[ERROR] ^^^^^^^^^^^^^^^^^^
[ERROR] The type Z80StandaloneSetup is already defined
[ERROR] /home/user/github-repositories/z80editor/org.efry.z80editor/src/org/efry/z80editor/Z80RuntimeModule.java:[12]
[ERROR] public class Z80RuntimeModule extends org.efry.z80editor.AbstractZ80RuntimeModule {
[ERROR] ^^^^^^^^^^^^^^^^
[ERROR] The type Z80RuntimeModule is already defined
[ERROR] 2 problems (2 errors)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.efry.z80editor
```
then each time I issue
`mvn package`
again, I get a new SUCCESS and a FAILURE on next step, until I get to the last one, where I just get this error:

```
[INFO] Reactor Summary:
[INFO] 
[INFO] org.efry.z80editor.parent .......................... SUCCESS [  0.051 s]
[INFO] org.efry.z80editor ................................. SUCCESS [ 31.304 s]
[INFO] org.efry.z80editor.ide ............................. SUCCESS [  2.298 s]
[INFO] org.efry.z80editor.ui .............................. SUCCESS [  1.714 s]
[INFO] org.efry.z80editor.target .......................... SUCCESS [  0.007 s]
[INFO] org.efry.z80editor.feature ......................... SUCCESS [  0.129 s]
[INFO] org.efry.z80editor.repository ...................... SUCCESS [  1.252 s]
[INFO] org.efry.z80editor.tests ........................... SUCCESS [  0.641 s]
[INFO] org.efry.z80editor.ui.tests ........................ FAILURE [  0.030 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 51.828 s
[INFO] Finished at: 2020-05-18T14:53:57+01:00
[INFO] Final Memory: 217M/900M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:1.5.1:package-plugin (default-package-plugin) on project org.efry.z80editor.ui.tests: /home/user/github-repositories/z80editor/org.efry.z80editor.ui.tests/build.properties: bin.includes value(s) must be specified.
```
